NLayerKSystem.WEB/Areas/Admin/Models/viewModel/SubjectViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TestEF.MyDbContext;

namespace NLayerKSystem.WEB.Areas.Admin.Models.viewModel
{
    public class SubjectViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int CountCredit { get; set; }
        public double Evaluation { get; set; }

        public int? EducationId { get; set; }
        public Education Education { get; set; }

        public int? NominationId { get; set; }
        public Nomination Nomination { get; set; }

        public int? KnowledgeId { get; set; }
        public Knowledge Knowledge { get; set; }

        public string EducationName
        {
            get
            {
                return Education?.Name ?? "";
            }
        }

        public IEnumerable<EducationViewModel> EducationViewModels { get; set; }

        public string NominationName
        {
            get
            {
                return Nomination?.Name ?? "";
            }
        }

        public IEnumerable<NominationViewModel> NominationViewModels { get; set; }

        public string KnowledgeName
        {
            get
            {
                return Knowledge?.Name ?? "";
            }
        }

        public IEnumerable<KnowledgeViewModel> KnowledgeViewModels { get; set; }
    }
}

NLayerKSystem.WEB/Models/viewModel/SubjectViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TestEF.MyDbContext;

namespace NLayerKSystem.WEB.Models.viewModel
{
    public class SubjectViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int CountCredit { get; set; }
        public double Evaluation { get; set; }

        public int? EducationId { get; set; }
        public Education Education { get; set; }

        public int? NominationId { get; set; }
        public Nomination Nomination { get; set; }

        public int? KnowledgeId { get; set; }
        public Knowledge Knowledge { get; set; }
    }
}

NLayerKSystem.WEB/Areas/Admin/Controllers/CityController.cs
using AutoMapper;
using NLayerKSystem.BLL.DTO;
using NLayerKSystem.BLL.Interface;
using NLayerKSystem.WEB.Areas.Admin.Models.pagingHelpers;
using NLayerKSystem.WEB.Areas.Admin.Models.viewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NLayerKSystem.WEB.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CityController : Controller
    {
        IService<CityDTO> cityService;
        IService<CountryDTO> countryService;

        public CityController(IService<CityDTO> cityService, IService<CountryDTO> countryService)
        {
            this.cityService = cityService;
            this.countryService = countryService;
        }

        public ActionResult Index(int page = 1)
        {
            int pageSize = 5;

            IEnumerable<CityDTO> cityDTO = cityService.GetTable().OrderByDescending(m => m.Id).Skip((page - 1) * pageSize).Take(pageSize);
            PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = cityService.GetTable().Count() };

            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<CityDTO, CityViewModel>()).CreateMapper();
            var city = mapper.Map<IEnumerable<CityDTO>, IEnumerable<CityViewModel>>(cityDTO);

            IEnumerable<CountryDTO> countryDTO = countryService.GetTable();
            var mapperCountry = new MapperConfiguration(cfg => cfg.CreateMap<CountryDTO, CountryViewModel>()).CreateMapper();
            var country = mapperCountry.Map<IEnumerable<CountryDTO>, IEnumerable<CountryViewModel>>(countryDTO);

            IndexViewModel<CityViewModel, CountryViewModel> ivm = new IndexViewModel<CityViewModel, CountryViewModel> { ListOfViewModel = city, PageInfo = pageInfo, ListOfViewModel2 = country };
                        
            return View(ivm);
        }
        
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(CityViewModel model)
        {
            if (model != null)
            {
                var cityDTO = new CityDTO
                {
                    Name = model.Name.Trim(),
                    CountryId = model.CountryId
                };

                cityService.Create(cityDTO);

                return RedirectToAction("Index");
            }

            return View();
        }
        
        [HttpPost]
        public ActionResult Delete(int id)
        {
            cityService.Delete(id);

            var redirectUrl = new UrlHelper(Request.RequestContext).Action("Index");

            return Json(new { Url = redirectUrl }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Edit()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Edit(CityViewModel model)
        {
            CityDTO city = new CityDTO
            {
                Id = model.Id,
                Name = model.Name.Trim(),
                CountryId = model.CountryId
            };

            cityService.Update(city);

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            cityService.Dispose();
            countryService.Dispose();
            base.Dispose(disposing);
        }
    }
}

NLayerKSystem.WEB/Areas/Admin/Controllers/SubjectController.cs
using AutoMapper;
using NLayerKSystem.BLL.DTO;
using NLayerKSystem.BLL.Interface;
using NLayerKSystem.WEB.Areas.Admin.Models.pagingHelpers;
using NLayerKSystem.WEB.Areas.Admin.Models.viewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NLayerKSystem.WEB.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SubjectController : Controller
    {
        IService<SubjectDTO> subjectService;
        IService<EducationDTO> educationService;
        IService<NominationDTO> nominationService;
        IService<KnowledgeDTO> knowledgeService;

        public SubjectController(IService<SubjectDTO> subjectService, IService<EducationDTO> educationService, IService<NominationDTO> nominationService, IService<KnowledgeDTO> knowledgeService)
        {
            this.subjectService = subjectService;
            this.educationService = educationService;
            this.nominationService = nominationService;
            this.knowledgeService = knowledgeService;
        }

        public ActionResult Index(int page = 1)
        {
            int pageSize = 5;

            IEnumerable<SubjectDTO> subjectDTO = subjectService.GetTable().OrderByDescending(m => m.Id).Skip((page - 1) * pageSize).Take(pageSize);
            PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = subjectService.GetTable().Count() };

            var mapperSubject = new MapperConfiguration(cfg => cfg.CreateMap<SubjectDTO, SubjectViewModel>()).CreateMapper();
            var subject = mapperSubject.Map<IEnumerable<SubjectDTO>, IEnumerable<SubjectViewModel>>(subjectDTO);

            IEnumerable<EducationDTO> educationDTO = educationService.GetTable();
            var mapperEducation = new MapperConfiguration(cfg => cfg.CreateMap<EducationDTO, EducationViewModel>()).CreateMapper();
            var education = mapperEducation.Map<IEnumerable<EducationDTO>, IEnumerable<EducationViewModel>>(educationDTO);

            IEnumerable<NominationDTO> nominationDTO = nominationService.GetTable();
            var mapperNomination = new MapperConfiguration(cfg => cfg.CreateMap<NominationDTO, NominationViewModel>()).CreateMapper();
            var nomination = mapperNomination.Map<IEnumerable<NominationDTO>, IEnumerable<NominationViewModel>>(nominationDTO);

            IEnumerable<KnowledgeDTO> knowledgeDTO = knowledgeService.GetTable();
            var mapperKnowledge = new MapperConfiguration(cfg => cfg.CreateMap<KnowledgeDTO, KnowledgeViewModel>()).CreateMapper();
            var knowledge = mapperKnowledge.Map<IEnumerable<KnowledgeDTO>, IEnumerable<KnowledgeViewModel>>(knowledgeDTO);

            IndexViewModel<SubjectViewModel, EducationViewModel, NominationViewModel, KnowledgeViewModel> ivm = new IndexViewModel<SubjectViewModel, EducationViewModel, NominationViewModel, KnowledgeViewModel> { ListOfViewModel = subject, ListOfViewModel2 = education, ListOfViewModel3 = nomination, ListOfViewModel4 = knowledge, PageInfo = pageInfo };

            return View(ivm);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(SubjectViewModel model)
        {
            if (model != null)
            {
                var subjectDTO = new SubjectDTO
                {
                    Name = model.Name.Trim(),
                    Description = model.Description.Trim(),
                    CountCredit = model.CountCredit,
                    Evaluation = model.Evaluation,
                    NominationId = model.NominationId,
                    EducationId = model.EducationId,
                    KnowledgeId = model.KnowledgeId
                };

                subjectService.Create(subjectDTO);

                ModelState.Clear();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            subjectService.Delete(id);

            var redirectUrl = new UrlHelper(Request.RequestContext).Action("Index");

            return Json(new { Url = redirectUrl }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Edit()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Edit(SubjectViewModel model)
        {
            var subjectDTO = new SubjectDTO
            {
                Id = model.Id,
                Name = model.Name.Trim(),
                Description = model.Description.Trim(),
                CountCredit = model.CountCredit,
                Evaluation = model.Evaluation,
                NominationId = model.NominationId,
                EducationId = model.EducationId,
                KnowledgeId = model.KnowledgeId
            };

            subjectService.Update(subjectDTO);

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            subjectService.Dispose();
            educationService.Dispose();
            nominationService.Dispose();
            knowledgeService.Dispose();
            base.Dispose(disposing);
        }
    }
}

NLayerKSystem.WEB/Areas/Admin/Views/Subject/Create.cshtml
@model NLayerKSystem.WEB.Areas.Admin.Models.viewModel.SubjectViewModel


@using (Html.BeginForm("Create", "Subject", FormMethod.Post))
{
	@Html.AntiForgeryToken()

<div class="form-horizontal">

	@Html.ValidationSummary(true, "", new { @class = "text-danger" })
	@Html.HiddenFor(model => model.Id)
	<div class="form-group">
		@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-3">
			@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-3">
			@Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.CountCredit, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-3">
			@Html.EditorFor(model => model.CountCredit, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.CountCredit, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.Evaluation, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-3">
			@Html.EditorFor(model => model.Evaluation, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Evaluation, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		<label class="control-label col-md-2">Nomination</label>
		<div class="col-md-3">
			@Html.DropDownListFor(model => model.NominationId, Model.NominationViewModels.Select(m => new SelectListItem() { Value = m.Id.ToString(), Text=m.Name }),
			new { @class = "form-control col-md-2"})
		</div>
	</div>

	<div class="form-group">
		<label class="control-label col-md-2">Education</label>
		<div class="col-md-3">
			@Html.DropDownListFor(model => model.EducationId, Model.EducationViewModels.Select(m => new SelectListItem() { Value = m.Id.ToString(), Text=m.Name }),
			new { @class = "form-control col-md-2"})
		</div>
	</div>

	<div class="form-group">
		<label class="control-label col-md-2">Knowledge</label>
		<div class="col-md-3">
			@Html.DropDownListFor(model => model.KnowledgeId, Model.KnowledgeViewModels.Select(m => new SelectListItem() { Value = m.Id.ToString(), Text=m.Name }),
			new { @class = "form-control col-md-2"})
		</div>
	</div>

	<div class="form-group">
		<div class="col-md-offset-2 col-md-4">
			<input type="submit" value="Create" class="btn btn-success" />
		</div>
	</div>
</div>
}

NLayerKSystem.WEB/Areas/Admin/Views/Subject/Edit.cshtml
@model NLayerKSystem.WEB.Areas.Admin.Models.viewModel.SubjectViewModel


@using (Html.BeginForm("Edit", "Subject", FormMethod.Post))
{
	@Html.AntiForgeryToken()
	<div class="modal-header">
		<a href="#" class="close" data-dismiss="modal">&times;</a>
		<h3 class="modal-title">Edit Subject</h3>
	</div>
	<div class="modal-body" style="margin-bottom: 20px">

		<div class="form-horizontal">

			@Html.ValidationSummary(true, "", new { @class = "text-danger" })
			@Html.HiddenFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })

			<div class="form-group">
				@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-3">
					@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-3">
					@Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.CountCredit, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-3">
					@Html.EditorFor(model => model.CountCredit, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.CountCredit, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.Evaluation, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-3">
					@Html.EditorFor(model => model.Evaluation, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.Evaluation, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				<label class="control-label col-md-2">Nomination</label>
				<div class="col-md-3">
					@Html.DropDownListFor(model => model.NominationId, Model.NominationViewModels.Select(m => new SelectListItem() { Value = m.Id.ToString(), Text=m.Name }),
					new { @class = "form-control col-md-2"})
				</div>
			</div>

			<div class="form-group">
				<label class="control-label col-md-2">Education</label>
				<div class="col-md-3">
					@Html.DropDownListFor(model => model.EducationId, Model.EducationViewModels.Select(m => new SelectListItem() { Value = m.Id.ToString(), Text=m.Name }),
					new { @class = "form-control col-md-2"})
				</div>
			</div>

			<div class="form-group">
				<label class="control-label col-md-2">Knowledge</label>
				<div class="col-md-3">
					@Html.DropDownListFor(model => model.KnowledgeId, Model.KnowledgeViewModels.Select(m => new SelectListItem() { Value = m.Id.ToString(), Text=m.Name }),
					new { @class = "form-control col-md-2"})
				</div>
			</div>
		</div>
	</div>
	<div class="modal-footer">
		<a href="#" class="btn btn-danger" data-dismiss="modal">Cancel</a>
		<input type="submit" value="Edit" class="btn btn-info" />
	</div>
}

NLayerKSystem.WEB/Areas/Admin/Views/Subject/Index.cshtml
@model IndexViewModel<SubjectViewModel, EducationViewModel, NominationViewModel, KnowledgeViewModel>

@using System.Linq;
@using NLayerKSystem.WEB.Areas.Admin.Models.pagingHelpers
@using NLayerKSystem.WEB.Areas.Admin.Models.viewModel
@{
	ViewBag.Title = "Admin";
	Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<body class="nav-md">
	<div class="container body">
		<div class="main_container">
			<div class="col-md-3 left_col">
				<div class="left_col scroll-view">
					<div class="navbar nav_title" style="border: 0;">
						<a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>KSystem</span></a>
					</div>
					<div class="clearfix"></div>
					<!-- menu profile quick info -->
					<div class="profile clearfix">
						<div class="profile_pic">
							<img src="~/Areas/production/images/img.jpg" alt="..." class="img-circle profile_img">
						</div>
						<div class="profile_info">
							<span>Welcome,</span>
							<h2>
								@(User.Identity.IsAuthenticated ? HttpContext.Current.User.Identity.Name : "Guest")
							</h2>
						</div>
					</div>
					<!-- /menu profile quick info -->
					<br />
					<!-- sidebar menu -->
					<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
						<div class="menu_section">
							<h3>General</h3>
							<ul class="nav side-menu">
								<li>
									<a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
									<ul class="nav child_menu">
										<li><a href="@Url.Action("Index","Home")">Admin Panel</a></li>
										<li><a href="@Url.Action("Index","Role")">Role</a></li>
										<li><a href="@Url.Action("Index","User")">User</a></li>
										<li><a href="@Url.Action("Index","Selection")">Selection</a></li>
										<li><a href="@Url.Action("Index","FinalSelection")">Final Selection</a></li>
									</ul>
								</li>
								<li>
									<a><i class="fa fa-table"></i> Tables <span class="fa fa-chevron-down"></span></a>
									<ul class="nav child_menu">
										<li><a href="@Url.Action("Index","City")">City</a></li>
										<li><a href="@Url.Action("Index","Country")">Country</a></li>
										<li><a href="@Url.Action("Index","Nomination")">Nomination</a></li>
										<li><a href="@Url.Action("Index","Subject")">Subject</a></li>
										<li><a href="@Url.Action("Index","Project")">Project</a></li>
										<li><a href="@Url.Action("Index","Knowledge")">Knowledge</a></li>
										<li><a href="@Url.Action("Index","Education")">Education</a></li>
										<li><a href="@Url.Action("Index","Experience")">Experience</a></li>
										<li><a href="@Url.Action("Index","Training")">Training</a></li>
										<li><a href="@Url.Action("Index","CertificationTest")">Certification Test</a></li>
										<li><a href="@Url.Action("Index","SportProgramming")">Sport Programming</a></li>
										<li><a href="@Url.Action("Index","Review")">Review/Comment</a></li>
									</ul>
								</li>
							</ul>
						</div>
					</div>
					<!-- /sidebar menu -->
				</div>
			</div>

			<!-- top navigation -->
			<div class="top_nav">
				<div class="nav_menu">
					<nav>
						<div class="nav toggle">
							<a id="menu_toggle"><i class="fa fa-bars"></i></a>
						</div>
						<ul class="nav navbar-nav navbar-right">
							<li class="">
								@if (User.Identity.IsAuthenticated)
								{
									<div class="col-sm-4" style="margin-top: 9px">
										<p>
											<a href="@Url.Action("SignOut", "Account",new { area = ""})" class="btn btn-default" style="float: right; color:black;">Sign out</a>
										</p>
									</div>
								}
							</li>
						</ul>
					</nav>
				</div>
			</div>
			<!-- /top navigation -->
			<!-- page content -->
			<div class="right_col" role="main">
				<div class="clearfix"></div>
				<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<div class="x_panel">
							<div class="x_title">
								<h2>Form <small>Subjects</small></h2>
								<ul class="nav navbar-right panel_toolbox">
									<li>
										<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
									</li>
								</ul>
								<div class="clearfix"></div>
							</div>

							@{ Html.RenderPartial("Create", new SubjectViewModel() { EducationViewModels = Model.ListOfViewModel2, NominationViewModels = Model.ListOfViewModel3, KnowledgeViewModels = Model.ListOfViewModel4 }); }

							<div style="text-align:center; display: none" id="loader">
								<img src="~/Content/setting.gif" width="150" />
							</div>

							<div class="x_content">
								<table id="datatable-buttons" class="table table-striped table-bordered">
									<thead>
										<tr>
											<th>Id</th>
											<th>Name</th>
											<th>Description</th>
											<th>Count Credit</th>
											<th>Evaluation</th>
											<th>Nomination Id</th>
											<th>Name</th>
											<th>Education Id</th>
											<th>Name</th>
											<th>Knowledge Id</th>
											<th>Name</th>
											<th>Parent Name</th>
											<th><i class="fa fa-edit"></i> | <i class="fa fa-trash"></i></th>
										</tr>
									</thead>

									<tbody>
										@foreach (var item in Model.ListOfViewModel)
										{
											<tr>
												<td>@Html.DisplayFor(model => item.Id)</td>
												<td>@Html.DisplayFor(model => item.Name)</td>
												<td><textarea>@Html.DisplayFor(model => item.Description)</textarea></td>
												<td>@Html.DisplayFor(model => item.CountCredit)</td>
												<td>@Html.DisplayFor(model => item.Evaluation)</td>
												<td>@Html.DisplayFor(model => item.NominationId)</td>
												<td><textarea>@Html.DisplayFor(model => item.NominationName)</textarea></td>
												<td>@Html.DisplayFor(model => item.EducationId)</td>
												<td>@Html.DisplayFor(model => item.EducationName)</td>
												<td>@Html.DisplayFor(model => item.KnowledgeId)</td>
												<td>@Html.DisplayFor(model => item.KnowledgeName)</td>
												<td>@Html.DisplayFor(model => item.Knowledge.Knowledge2.Name)</td>
												<td>
													<a class="btn btn-info" data-target="#myModal_@item.Id" data-toggle="modal"><i class="fa fa-pencil"></i></a>
													<a class="btn btn-danger" onclick="Delete('@Url.Action("Delete","Subject", new { id = item.Id})')"><i class="fa fa-trash"></i></a>

													<div class="modal active" id="myModal_@item.Id">
														<div class="modal-dialog">
															<div class="modal-content">
																@{ Html.RenderPartial("Edit", new SubjectViewModel()
																	{
																		Id = item.Id,
																		Name = item.Name,
																		Description = item.Description,
																		Evaluation = item.Evaluation,
																		CountCredit = item.CountCredit,
																		EducationViewModels = Model.ListOfViewModel2,
																		NominationViewModels = Model.ListOfViewModel3,
																		KnowledgeViewModels = Model.ListOfViewModel4
																	}); }
															</div>
														</div>
													</div>
												</td>
											</tr>
										}
									</tbody>
								</table>

								<div class="btn-group">
									@Html.PageLinks(Model.PageInfo, x => Url.Action("Index", new { page = x }))
								</div>

							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- /page content -->

		</div>
	</div>

</body>

<script>

	function Delete(url, id) {
		if (confirm('Are you sure to delete this record ?')) {
			$.ajax({
				type: 'POST',
				url: url,
				success: function (data) {
					window.location.reload();
				}
			});
		}
	}

</script>