NLayerKSystem.WEB/Areas/Admin/Models/viewModel/EducationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TestEF.MyDbContext;

namespace NLayerKSystem.WEB.Areas.Admin.Models.viewModel
{
    public class EducationViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double GPA { get; set; }
        public string DiplomaPhoto { get; set; }
      
        public int? CityId { get; set; }
        public City City { get; set; }

        public int? UserId { get; set; }
        public User User { get; set; }
        
        public HttpPostedFileBase ImageFile { get; set; }

        public string CityName
        {
            get
            {
                return City?.Name ?? "";
            }
        }

        public IEnumerable<CityViewModel> CityViewModels { get; set; }

        public string UserName
        {
            get
            {
                return User?.Name ?? "";
            }
        }

        public IEnumerable<UserViewModel> UserViewModels { get; set; }
    }
}

NLayerKSystem.WEB/Models/viewModel/EducationViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using TestEF.MyDbContext;

namespace NLayerKSystem.WEB.Models.viewModel
{
    public class EducationViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Не указано")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Недопустимая длина имени")]
        public string Name { get; set; }
        
        [Range(1, 4, ErrorMessage = "Please enter a value bigger than 0")]
        public double GPA { get; set; }

        public string DiplomaPhoto { get; set; }

        public int? CityId { get; set; }
        public City City { get; set; }

        public int? UserId { get; set; }
        public User User { get; set; }

        [Required(ErrorMessage = "Photo is required")]
        public HttpPostedFileBase ImageFile { get; set; }

        public string CityName
        {
            get
            {
                return City?.Name ?? "";
            }
        }

        public IEnumerable<CityViewModel> CityViewModels { get; set; }

        public string UserName
        {
            get
            {
                return User?.Name ?? "";
            }
        }

        public IEnumerable<UserViewModel> UserViewModels { get; set; }
    }
}

NLayerKSystem.WEB/Areas/Admin/Controllers/CityController.cs
using AutoMapper;
using NLayerKSystem.BLL.DTO;
using NLayerKSystem.BLL.Interface;
using NLayerKSystem.WEB.Areas.Admin.Models.pagingHelpers;
using NLayerKSystem.WEB.Areas.Admin.Models.viewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NLayerKSystem.WEB.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CityController : Controller
    {
        IService<CityDTO> cityService;
        IService<CountryDTO> countryService;

        public CityController(IService<CityDTO> cityService, IService<CountryDTO> countryService)
        {
            this.cityService = cityService;
            this.countryService = countryService;
        }

        public ActionResult Index(int page = 1)
        {
            int pageSize = 5;

            IEnumerable<CityDTO> cityDTO = cityService.GetTable().OrderByDescending(m => m.Id).Skip((page - 1) * pageSize).Take(pageSize);
            PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = cityService.GetTable().Count() };

            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<CityDTO, CityViewModel>()).CreateMapper();
            var city = mapper.Map<IEnumerable<CityDTO>, IEnumerable<CityViewModel>>(cityDTO);

            IEnumerable<CountryDTO> countryDTO = countryService.GetTable();
            var mapperCountry = new MapperConfiguration(cfg => cfg.CreateMap<CountryDTO, CountryViewModel>()).CreateMapper();
            var country = mapperCountry.Map<IEnumerable<CountryDTO>, IEnumerable<CountryViewModel>>(countryDTO);

            IndexViewModel<CityViewModel, CountryViewModel> ivm = new IndexViewModel<CityViewModel, CountryViewModel> { ListOfViewModel = city, PageInfo = pageInfo, ListOfViewModel2 = country };
                        
            return View(ivm);
        }
        
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(CityViewModel model)
        {
            if (model != null)
            {
                var cityDTO = new CityDTO
                {
                    Name = model.Name.Trim(),
                    CountryId = model.CountryId
                };

                cityService.Create(cityDTO);

                return RedirectToAction("Index");
            }

            return View();
        }
        
        [HttpPost]
        public ActionResult Delete(int id)
        {
            cityService.Delete(id);

            var redirectUrl = new UrlHelper(Request.RequestContext).Action("Index");

            return Json(new { Url = redirectUrl }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Edit()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Edit(CityViewModel model)
        {
            CityDTO city = new CityDTO
            {
                Id = model.Id,
                Name = model.Name.Trim(),
                CountryId = model.CountryId
            };

            cityService.Update(city);

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            cityService.Dispose();
            countryService.Dispose();
            base.Dispose(disposing);
        }
    }
}

NLayerKSystem.WEB/Areas/Admin/Controllers/EducationController.cs
using AutoMapper;
using NLayerKSystem.BLL.DTO;
using NLayerKSystem.BLL.Interface;
using NLayerKSystem.WEB.Areas.Admin.Models.pagingHelpers;
using NLayerKSystem.WEB.Areas.Admin.Models.viewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NLayerKSystem.WEB.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class EducationController : Controller
    {
        IService<EducationDTO> educationService;
        IService<UserDTO> userService;
        IService<CityDTO> cityService;

        public EducationController(IService<EducationDTO> educationService, IService<UserDTO> userService, IService<CityDTO> cityService)
        {
            this.educationService = educationService;
            this.userService = userService;
            this.cityService = cityService;
        }

        public ActionResult Index(int page = 1)
        {
            int pageSize = 5;

            IEnumerable<EducationDTO> educationDTO = educationService.GetTable().OrderByDescending(m => m.Id).Skip((page - 1) * pageSize).Take(pageSize);

            PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = educationService.GetTable().Count() };

            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<EducationDTO, EducationViewModel>()).CreateMapper();
            var education = mapper.Map<IEnumerable<EducationDTO>, IEnumerable<EducationViewModel>>(educationDTO);

            IEnumerable<UserDTO> userDTO = userService.GetTable();
            var mapperUser = new MapperConfiguration(cfg => cfg.CreateMap<UserDTO, UserViewModel>()).CreateMapper();
            var user = mapperUser.Map<IEnumerable<UserDTO>, IEnumerable<UserViewModel>>(userDTO);

            IEnumerable<CityDTO> cityDTO = cityService.GetTable();
            var mapperCity = new MapperConfiguration(cfg => cfg.CreateMap<CityDTO, CityViewModel>()).CreateMapper();
            var city = mapperCity.Map<IEnumerable<CityDTO>, IEnumerable<CityViewModel>>(cityDTO);

            IndexViewModel<EducationViewModel, UserViewModel, CityViewModel> ivm = new IndexViewModel<EducationViewModel, UserViewModel, CityViewModel> { ListOfViewModel = education, ListOfViewModel2 = user, ListOfViewModel3 = city, PageInfo = pageInfo, };

            return View(ivm);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(EducationViewModel model)
        {
            if (model != null)
            {
                var fileName = Path.GetFileNameWithoutExtension(model.ImageFile.FileName);
                var extension = Path.GetExtension(model.ImageFile.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                model.DiplomaPhoto = "~/Areas/production/images/" + fileName;
                fileName = Path.Combine(Server.MapPath("~/Areas/production/images/"), fileName);
                model.ImageFile.SaveAs(fileName);

                var educationDTO = new EducationDTO
                {
                    Name = model.Name.Trim(),
                    GPA = model.GPA,
                    DiplomaPhoto = model.DiplomaPhoto.Trim(),
                    CityId = model.CityId,
                    UserId = model.UserId
                };

                educationService.Create(educationDTO);

                ModelState.Clear();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            educationService.Delete(id);

            var redirectUrl = new UrlHelper(Request.RequestContext).Action("Index");

            return Json(new { Url = redirectUrl }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Edit()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Edit(EducationViewModel model)
        {
            var fileName = Path.GetFileNameWithoutExtension(model.ImageFile.FileName);
            var extension = Path.GetExtension(model.ImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            model.DiplomaPhoto = "~/Areas/production/images/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Areas/production/images/"), fileName);
            model.ImageFile.SaveAs(fileName);

            var educationDTO = new EducationDTO
            {
                Id = model.Id,
                Name = model.Name.Trim(),
                GPA = model.GPA,
                DiplomaPhoto = model.DiplomaPhoto.Trim(),
                CityId = model.CityId,
                UserId = model.UserId
            };

            educationService.Update(educationDTO);

            ModelState.Clear();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            userService.Dispose();
            educationService.Dispose();
            cityService.Dispose();
            base.Dispose(disposing);
        }
    }
}

NLayerKSystem.WEB/Areas/Admin/Views/Education/Create.cshtml
@model NLayerKSystem.WEB.Areas.Admin.Models.viewModel.EducationViewModel

@using (Html.BeginForm("Create", "Education", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">

		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		@Html.HiddenFor(model => model.Id)
		@Html.HiddenFor(model => model.DiplomaPhoto)
		<div class="form-group">
			@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-3">
				@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.GPA, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-3">
				@Html.EditorFor(model => model.GPA, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.GPA, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.DiplomaPhoto, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-3">
				@Html.TextBoxFor(model => model.ImageFile, new { type = "file", accept = "image/x-png, image/gif, image/jpeg, image/jpg", htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.ImageFile, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			<label class="control-label col-md-2">City</label>
			<div class="col-md-3">
				@Html.DropDownListFor(model => model.CityId, Model.CityViewModels.Select(m => new SelectListItem() { Value = m.Id.ToString(), Text=m.Name }),
				new { @class = "form-control col-md-2"})
			</div>
		</div>

		<div class="form-group">
			<label class="control-label col-md-2">User</label>
			<div class="col-md-3">
				@Html.DropDownListFor(model => model.UserId, Model.UserViewModels.Select(m => new SelectListItem() { Value = m.Id.ToString(), Text=m.Name }),
				new { @class = "form-control col-md-2"})
			</div>
		</div>

		<div class="form-group">
			<div class="col-md-offset-2 col-md-4">
				<input type="submit" value="Create" class="btn btn-success" />
			</div>
		</div>
	</div>
}

NLayerKSystem.WEB/Areas/Admin/Views/Education/Edit.cshtml
@model NLayerKSystem.WEB.Areas.Admin.Models.viewModel.EducationViewModel

@using (Html.BeginForm("Edit", "Education", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
	@Html.AntiForgeryToken()

	<div class="modal-header">
		<a href="#" class="close" data-dismiss="modal">&times;</a>
		<h3 class="modal-title">Edit Education</h3>
	</div>
	<div class="modal-body" style="margin-bottom: 20px">
		<div class="form-horizontal">

			@Html.ValidationSummary(true, "", new { @class = "text-danger" })
			@Html.HiddenFor(model => model.Id)
			@Html.HiddenFor(model => model.DiplomaPhoto)
			<div class="form-group">
				@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-3">
					@Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.GPA, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-3">
					@Html.EditorFor(model => model.GPA, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.GPA, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.DiplomaPhoto, htmlAttributes: new { @class = "control-label col-md-2" })
				<div class="col-md-3">
					@Html.TextBoxFor(model => model.ImageFile, new { type = "file", accept = "image/x-png, image/gif, image/jpeg, image/jpg", htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.ImageFile, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				<label class="control-label col-md-2">City</label>
				<div class="col-md-3">
					@Html.DropDownListFor(model => model.CityId, Model.CityViewModels.Select(m => new SelectListItem() { Value = m.Id.ToString(), Text=m.Name }),
					new { @class = "form-control col-md-2"})
				</div>
			</div>

			<div class="form-group">
				<label class="control-label col-md-2">User</label>
				<div class="col-md-3">
					@Html.DropDownListFor(model => model.UserId, Model.UserViewModels.Select(m => new SelectListItem() { Value = m.Id.ToString(), Text=m.Name }),
					new { @class = "form-control col-md-2"})
				</div>
			</div>

		</div>
	</div>
	<div class="modal-footer">
		<a href="#" class="btn btn-danger" data-dismiss="modal">Cancel</a>
		<input type="submit" value="Edit" class="btn btn-info" />
	</div>
}

NLayerKSystem.WEB/Areas/Admin/Views/Education/Index.cshtml
@model IndexViewModel<EducationViewModel, UserViewModel, CityViewModel>

@using System.Linq;
@using NLayerKSystem.WEB.Areas.Admin.Models.pagingHelpers
@using NLayerKSystem.WEB.Areas.Admin.Models.viewModel
@{
	ViewBag.Title = "Admin";
	Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<body class="nav-md">
	<div class="container body">
		<div class="main_container">
			<div class="col-md-3 left_col">
				<div class="left_col scroll-view">
					<div class="navbar nav_title" style="border: 0;">
						<a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>KSystem</span></a>
					</div>
					<div class="clearfix"></div>
					<!-- menu profile quick info -->
					<div class="profile clearfix">
						<div class="profile_pic">
							<img src="~/Areas/production/images/img.jpg" alt="..." class="img-circle profile_img">
						</div>
						<div class="profile_info">
							<span>Welcome,</span>
							<h2>
								@(User.Identity.IsAuthenticated ? HttpContext.Current.User.Identity.Name : "Guest")
							</h2>
						</div>
					</div>
					<!-- /menu profile quick info -->
					<br />
					<!-- sidebar menu -->
					<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
						<div class="menu_section">
							<h3>General</h3>
							<ul class="nav side-menu">
								<li>
									<a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
									<ul class="nav child_menu">
										<li><a href="@Url.Action("Index","Home")">Admin Panel</a></li>
										<li><a href="@Url.Action("Index","Role")">Role</a></li>
										<li><a href="@Url.Action("Index","User")">User</a></li>
										<li><a href="@Url.Action("Index","Selection")">Selection</a></li>
										<li><a href="@Url.Action("Index","FinalSelection")">Final Selection</a></li>
									</ul>
								</li>
								<li>
									<a><i class="fa fa-table"></i> Tables <span class="fa fa-chevron-down"></span></a>
									<ul class="nav child_menu">
										<li><a href="@Url.Action("Index","City")">City</a></li>
										<li><a href="@Url.Action("Index","Country")">Country</a></li>
										<li><a href="@Url.Action("Index","Nomination")">Nomination</a></li>
										<li><a href="@Url.Action("Index","Subject")">Subject</a></li>
										<li><a href="@Url.Action("Index","Project")">Project</a></li>
										<li><a href="@Url.Action("Index","Knowledge")">Knowledge</a></li>
										<li><a href="@Url.Action("Index","Education")">Education</a></li>
										<li><a href="@Url.Action("Index","Experience")">Experience</a></li>
										<li><a href="@Url.Action("Index","Training")">Training</a></li>
										<li><a href="@Url.Action("Index","CertificationTest")">Certification Test</a></li>
										<li><a href="@Url.Action("Index","SportProgramming")">Sport Programming</a></li>
										<li><a href="@Url.Action("Index","Review")">Review/Comment</a></li>
									</ul>
								</li>
							</ul>
						</div>
					</div>
					<!-- /sidebar menu -->
				</div>
			</div>

			<!-- top navigation -->
			<div class="top_nav">
				<div class="nav_menu">
					<nav>
						<div class="nav toggle">
							<a id="menu_toggle"><i class="fa fa-bars"></i></a>
						</div>
						<ul class="nav navbar-nav navbar-right">
							<li class="">
								@if (User.Identity.IsAuthenticated)
								{
									<div class="col-sm-4" style="margin-top: 9px">
										<p>
											<a href="@Url.Action("SignOut", "Account",new { area = ""})" class="btn btn-default" style="float: right; color:black;">Sign out</a>
										</p>
									</div>
								}
							</li>
						</ul>
					</nav>
				</div>
			</div>
			<!-- /top navigation -->
			<!-- page content -->
			<div class="right_col" role="main">
				<div class="clearfix"></div>
				<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<div class="x_panel">
							<div class="x_title">
								<h2>Form <small>Educations</small></h2>
								<ul class="nav navbar-right panel_toolbox">
									<li>
										<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
									</li>
								</ul>
								<div class="clearfix"></div>
							</div>

							@{ Html.RenderPartial("Create", new EducationViewModel() { UserViewModels = Model.ListOfViewModel2, CityViewModels = Model.ListOfViewModel3 }); }

							<div style="text-align:center; display: none" id="loader">
								<img src="~/Content/setting.gif" width="150" />
							</div>

							<div class="x_content">
								<table id="datatable-buttons" class="table table-striped table-bordered">
									<thead>
										<tr>
											<th>Id</th>
											<th>Education Name</th>
											<th>GPA</th>
											<th>Diploma Photo</th>
											<th>Country</th>
											<th>City Id</th>
											<th>City</th>
											<th>User Id</th>
											<th>User</th>
											<th><i class="fa fa-edit"></i> | <i class="fa fa-trash"></i></th>
										</tr>
									</thead>

									<tbody>
										@foreach (var item in Model.ListOfViewModel)
										{
											<tr>
												<td>@Html.DisplayFor(model => item.Id)</td>
												<td>@Html.DisplayFor(model => item.Name)</td>
												<td>@Html.DisplayFor(model => item.GPA)</td>
												<td><img src="@Url.Content(item.DiplomaPhoto)" width="50" height="50" style="display:block; margin-left: auto; margin-right: auto;" /></td>
												<td>@Html.DisplayFor(model => item.City.Country.Name)</td>
												<td>@Html.DisplayFor(model => item.CityId)</td>
												<td>@Html.DisplayFor(model => item.CityName)</td>
												<td>@Html.DisplayFor(model => item.UserId)</td>
												<td>@Html.DisplayFor(model => item.UserName)</td>
												<td>
													<a class="btn btn-info" data-target="#myModal_@item.Id" data-toggle="modal"><i class="fa fa-pencil"></i></a>
													<a class="btn btn-danger" onclick="Delete('@Url.Action("Delete","Education", new { id = item.Id})')"><i class="fa fa-trash"></i></a>

													<div class="modal active" id="myModal_@item.Id">
														<div class="modal-dialog">
															<div class="modal-content">
																@{ Html.RenderPartial("Edit", new EducationViewModel()
																	{
																		UserViewModels = Model.ListOfViewModel2,
																		CityViewModels = Model.ListOfViewModel3,
																		Id = item.Id,
																		Name = item.Name,
																		GPA = item.GPA,
																		DiplomaPhoto = item.DiplomaPhoto
																	}); }
															</div>
														</div>
													</div>
												</td>
											</tr>
										}
									</tbody>
								</table>

								<div class="btn-group">
									@Html.PageLinks(Model.PageInfo, x => Url.Action("Index", new { page = x }))
								</div>

							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- /page content -->

		</div>
	</div>

</body>

<script>

	function Delete(url, id) {
		if (confirm('Are you sure to delete this record ?')) {
			$.ajax({
				type: 'POST',
				url: url,
				success: function (data) {
					window.location.reload();
				}
			});
		}
	}

</script>