NLayerKSystem.WEB/Areas/Admin/Models/viewModel/ExperienceViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TestEF.MyDbContext;

namespace NLayerKSystem.WEB.Areas.Admin.Models.viewModel
{
    public class ExperienceViewModel
    {
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string CountExperience { get; set; }

        public int? CityId { get; set; }
        public City City { get; set; }
        public int? KnowledgeId { get; set; }
        public Knowledge Knowledge { get; set; }
        public int? UserId { get; set; }
        public User User { get; set; }

        public string CityName
        {
            get
            {
                return City?.Name ?? "";
            }
        }

        public IEnumerable<CityViewModel> CityViewModels { get; set; }

        public string KnowledgeName
        {
            get
            {
                return Knowledge?.Name ?? "";
            }
        }

        public IEnumerable<KnowledgeViewModel> KnowledgeViewModels { get; set; }

        public string UserName
        {
            get
            {
                return User?.Name ?? "";
            }
        }

        public IEnumerable<UserViewModel> UserViewModels { get; set; }
    }
}

NLayerKSystem.WEB/Models/viewModel/ExperienceViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TestEF.MyDbContext;

namespace NLayerKSystem.WEB.Models.viewModel
{
    public class ExperienceViewModel
    {
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string CountExperience { get; set; }

        public int? CityId { get; set; }
        public City City { get; set; }
        public int? KnowledgeId { get; set; }
        public Knowledge Knowledge1 { get; set; }
        public int? UserId { get; set; }
        public User User { get; set; }

        public string KnowledgeName
        {
            get
            {
                return Knowledge1?.Name ?? "";
            }
        }

        public IEnumerable<KnowledgeViewModel> KnowledgeViewModels { get; set; }
        public IEnumerable<UserViewModel> UserViewModels { get; set; }
        public IEnumerable<CityViewModel> CityViewModels { get; set; }
    }
}

NLayerKSystem.WEB/Areas/Admin/Controllers/CityController.cs
using AutoMapper;
using NLayerKSystem.BLL.DTO;
using NLayerKSystem.BLL.Interface;
using NLayerKSystem.WEB.Areas.Admin.Models.pagingHelpers;
using NLayerKSystem.WEB.Areas.Admin.Models.viewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NLayerKSystem.WEB.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CityController : Controller
    {
        IService<CityDTO> cityService;
        IService<CountryDTO> countryService;

        public CityController(IService<CityDTO> cityService, IService<CountryDTO> countryService)
        {
            this.cityService = cityService;
            this.countryService = countryService;
        }

        public ActionResult Index(int page = 1)
        {
            int pageSize = 5;

            IEnumerable<CityDTO> cityDTO = cityService.GetTable().OrderByDescending(m => m.Id).Skip((page - 1) * pageSize).Take(pageSize);
            PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = cityService.GetTable().Count() };

            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<CityDTO, CityViewModel>()).CreateMapper();
            var city = mapper.Map<IEnumerable<CityDTO>, IEnumerable<CityViewModel>>(cityDTO);

            IEnumerable<CountryDTO> countryDTO = countryService.GetTable();
            var mapperCountry = new MapperConfiguration(cfg => cfg.CreateMap<CountryDTO, CountryViewModel>()).CreateMapper();
            var country = mapperCountry.Map<IEnumerable<CountryDTO>, IEnumerable<CountryViewModel>>(countryDTO);

            IndexViewModel<CityViewModel, CountryViewModel> ivm = new IndexViewModel<CityViewModel, CountryViewModel> { ListOfViewModel = city, PageInfo = pageInfo, ListOfViewModel2 = country };
                        
            return View(ivm);
        }
        
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(CityViewModel model)
        {
            if (model != null)
            {
                var cityDTO = new CityDTO
                {
                    Name = model.Name.Trim(),
                    CountryId = model.CountryId
                };

                cityService.Create(cityDTO);

                return RedirectToAction("Index");
            }

            return View();
        }
        
        [HttpPost]
        public ActionResult Delete(int id)
        {
            cityService.Delete(id);

            var redirectUrl = new UrlHelper(Request.RequestContext).Action("Index");

            return Json(new { Url = redirectUrl }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Edit()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Edit(CityViewModel model)
        {
            CityDTO city = new CityDTO
            {
                Id = model.Id,
                Name = model.Name.Trim(),
                CountryId = model.CountryId
            };

            cityService.Update(city);

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            cityService.Dispose();
            countryService.Dispose();
            base.Dispose(disposing);
        }
    }
}

NLayerKSystem.WEB/Areas/Admin/Controllers/ExperienceController.cs
using AutoMapper;
using NLayerKSystem.BLL.DTO;
using NLayerKSystem.BLL.Interface;
using NLayerKSystem.WEB.Areas.Admin.Models.pagingHelpers;
using NLayerKSystem.WEB.Areas.Admin.Models.viewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NLayerKSystem.WEB.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ExperienceController : Controller
    {
        IService<ExperienceDTO> experienceService;
        IService<CityDTO> cityService;
        IService<UserDTO> userService;
        IService<KnowledgeDTO> knowledgeService;

        public ExperienceController(IService<ExperienceDTO> experienceService, IService<CityDTO> cityService, IService<UserDTO> userService, IService<KnowledgeDTO> knowledgeService)
        {
            this.experienceService = experienceService;
            this.cityService = cityService;
            this.userService = userService;
            this.knowledgeService = knowledgeService;
        }

        public ActionResult Index(int page = 1)
        {
            int pageSize = 5;

            IEnumerable<ExperienceDTO> experienceDTO = experienceService.GetTable().OrderByDescending(m => m.Id).Skip((page - 1) * pageSize).Take(pageSize);
            PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = experienceService.GetTable().Count() };

            var mapperExperince = new MapperConfiguration(cfg => cfg.CreateMap<ExperienceDTO, ExperienceViewModel>()).CreateMapper();
            var experience = mapperExperince.Map<IEnumerable<ExperienceDTO>, IEnumerable<ExperienceViewModel>>(experienceDTO);

            IEnumerable<CityDTO> cityDTO = cityService.GetTable();
            var mapperCity = new MapperConfiguration(cfg => cfg.CreateMap<CityDTO, CityViewModel>()).CreateMapper();
            var city = mapperCity.Map<IEnumerable<CityDTO>, IEnumerable<CityViewModel>>(cityDTO);

            IEnumerable<UserDTO> userDTO = userService.GetTable();
            var mapperUser = new MapperConfiguration(cfg => cfg.CreateMap<UserDTO, UserViewModel>()).CreateMapper();
            var user = mapperUser.Map<IEnumerable<UserDTO>, IEnumerable<UserViewModel>>(userDTO);

            IEnumerable<KnowledgeDTO> knowledgeDTO = knowledgeService.GetTable();
            var mapperKnowledge = new MapperConfiguration(cfg => cfg.CreateMap<KnowledgeDTO, KnowledgeViewModel>()).CreateMapper();
            var knowledge = mapperKnowledge.Map<IEnumerable<KnowledgeDTO>, IEnumerable<KnowledgeViewModel>>(knowledgeDTO);

            IndexViewModel<ExperienceViewModel, CityViewModel, UserViewModel, KnowledgeViewModel> ivm = new IndexViewModel<ExperienceViewModel, CityViewModel, UserViewModel, KnowledgeViewModel>
            { ListOfViewModel = experience, ListOfViewModel2 = city, ListOfViewModel3 = user, ListOfViewModel4 = knowledge, PageInfo = pageInfo };

            return View(ivm);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(ExperienceViewModel model)
        {
            if (model != null)
            {
                var experienceDTO = new ExperienceDTO
                {
                    CompanyName = model.CompanyName.Trim(),
                    CountExperience = model.CountExperience.Trim(),
                    CityId = model.CityId,
                    KnowledgeId = model.KnowledgeId,
                    UserId = model.UserId
                };

                experienceService.Create(experienceDTO);

                ModelState.Clear();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            experienceService.Delete(id);

            var redirectUrl = new UrlHelper(Request.RequestContext).Action("Index");

            return Json(new { Url = redirectUrl }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Edit()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Edit(ExperienceViewModel model)
        {
            var experienceDTO = new ExperienceDTO
            {
                Id = model.Id,
                CompanyName = model.CompanyName.Trim(),
                CountExperience = model.CountExperience.Trim(),
                CityId = model.CityId,
                KnowledgeId = model.KnowledgeId,
                UserId = model.UserId
            };

            experienceService.Update(experienceDTO);

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            experienceService.Dispose();
            cityService.Dispose();
            userService.Dispose();
            knowledgeService.Dispose();
            base.Dispose(disposing);
        }
    }
}

NLayerKSystem.WEB/Areas/Admin/Views/Experience/Create.cshtml
@model NLayerKSystem.WEB.Areas.Admin.Models.viewModel.ExperienceViewModel

@using (Html.BeginForm("Create", "Experience", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		@Html.HiddenFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })

		<div class="form-group">
			<label class="control-label col-md-2">Company Name</label>
			<div class="col-md-4">
				@Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			<label class="control-label col-md-2">Count Experience</label>
			<div class="col-md-4">
				@Html.EditorFor(model => model.CountExperience, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.CountExperience, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			<label class="control-label col-md-2">City</label>
			<div class="col-md-4">
				@Html.DropDownListFor(model => model.CityId, Model.CityViewModels.Select(m => new SelectListItem() { Value = m.Id.ToString(), Text=m.Name }),
				new { @class = "form-control col-md-2"})
			</div>
		</div>

		<div class="form-group">
			<label class="control-label col-md-2">Knowledge</label>
			<div class="col-md-4">
				@Html.DropDownListFor(model => model.KnowledgeId, Model.KnowledgeViewModels.Select(m => new SelectListItem() { Value = m.Id.ToString(), Text=m.Name }),
				new { @class = "form-control col-md-2"})
			</div>
		</div>

		<div class="form-group">
			<label class="control-label col-md-2">User</label>
			<div class="col-md-4">
				@Html.DropDownListFor(model => model.UserId, Model.UserViewModels.Select(m => new SelectListItem() { Value = m.Id.ToString(), Text=m.Name }),
				new { @class = "form-control col-md-2"})
			</div>
		</div>

		<div class="form-group">
			<div class="col-md-offset-2 col-md-2">
				<input type="submit" value="Create" class="btn btn-default" />
			</div>
		</div>
	</div>
}

NLayerKSystem.WEB/Areas/Admin/Views/Experience/Edit.cshtml
@model NLayerKSystem.WEB.Areas.Admin.Models.viewModel.ExperienceViewModel


@using (Html.BeginForm("Edit", "Experience", FormMethod.Post))
{
	@Html.AntiForgeryToken()
	<div class="modal-header">
		<a href="#" class="close" data-dismiss="modal">&times;</a>
		<h3 class="modal-title">Edit Experience</h3>
	</div>
	<div class="modal-body" style="margin-bottom: 20px">
		<div class="form-horizontal">

			@Html.ValidationSummary(true, "", new { @class = "text-danger" })
			@Html.HiddenFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
			<div class="form-group">
				<label class="control-label col-md-3">Company Name</label>
				<div class="col-md-3">
					@Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				<label class="control-label col-md-3">Count Experience</label>
				<div class="col-md-3">
					@Html.TextAreaFor(model => model.CountExperience, new { htmlAttributes = new { @class = "form-control" } })
					@Html.ValidationMessageFor(model => model.CountExperience, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				<label class="control-label col-md-3">City</label>
				<div class="col-md-3">
					@Html.DropDownListFor(model => model.CityId, Model.CityViewModels.Select(m => new SelectListItem() { Value = m.Id.ToString(), Text=m.Name }),
					new { @class = "form-control col-md-2"})
				</div>
			</div>

			<div class="form-group">
				<label class="control-label col-md-3">Knowledge</label>
				<div class="col-md-3">
					@Html.DropDownListFor(model => model.KnowledgeId, Model.KnowledgeViewModels.Select(m => new SelectListItem() { Value = m.Id.ToString(), Text=m.Name }),
					new { @class = "form-control col-md-2"})
				</div>
			</div>

			<div class="form-group">
				<label class="control-label col-md-3">User</label>
				<div class="col-md-5">
					@Html.DropDownListFor(model => model.UserId, Model.UserViewModels.Select(m => new SelectListItem() { Value = m.Id.ToString(), Text=m.Name }),
					new { @class = "form-control col-md-2"})
				</div>
			</div>

		</div>
	</div>
	<div class="modal-footer">
		<a href="#" class="btn btn-danger" data-dismiss="modal">Cancel</a>
		<input type="submit" value="Edit" class="btn btn-info" />
	</div>
}

NLayerKSystem.WEB/Areas/Admin/Views/Experience/Index.cshtml
@model NLayerKSystem.WEB.Areas.Admin.Models.viewModel.IndexViewModel<ExperienceViewModel, CityViewModel, UserViewModel, KnowledgeViewModel>

@using System.Linq;
@using NLayerKSystem.WEB.Areas.Admin.Models.pagingHelpers
@using NLayerKSystem.WEB.Areas.Admin.Models.viewModel
@{
	ViewBag.Title = "Admin";
	Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<body class="nav-md">
	<div class="container body">
		<div class="main_container">
			<div class="col-md-3 left_col">
				<div class="left_col scroll-view">
					<div class="navbar nav_title" style="border: 0;">
						<a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>KSystem</span></a>
					</div>
					<div class="clearfix"></div>
					<!-- menu profile quick info -->
					<div class="profile clearfix">
						<div class="profile_pic">
							<img src="~/Areas/production/images/img.jpg" alt="..." class="img-circle profile_img">
						</div>
						<div class="profile_info">
							<span>Welcome,</span>
							<h2>
								@(User.Identity.IsAuthenticated ? HttpContext.Current.User.Identity.Name : "Guest")
							</h2>
						</div>
					</div>
					<!-- /menu profile quick info -->
					<br />
					<!-- sidebar menu -->
					<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
						<div class="menu_section">
							<h3>General</h3>
							<ul class="nav side-menu">
								<li>
									<a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
									<ul class="nav child_menu">
										<li><a href="@Url.Action("Index","Home")">Admin Panel</a></li>
										<li><a href="@Url.Action("Index","Role")">Role</a></li>
										<li><a href="@Url.Action("Index","User")">User</a></li>
										<li><a href="@Url.Action("Index","Selection")">Selection</a></li>
										<li><a href="@Url.Action("Index","FinalSelection")">Final Selection</a></li>
									</ul>
								</li>
								<li>
									<a><i class="fa fa-table"></i> Tables <span class="fa fa-chevron-down"></span></a>
									<ul class="nav child_menu">
										<li><a href="@Url.Action("Index","City")">City</a></li>
										<li><a href="@Url.Action("Index","Country")">Country</a></li>
										<li><a href="@Url.Action("Index","Nomination")">Nomination</a></li>
										<li><a href="@Url.Action("Index","Subject")">Subject</a></li>
										<li><a href="@Url.Action("Index","Project")">Project</a></li>
										<li><a href="@Url.Action("Index","Knowledge")">Knowledge</a></li>
										<li><a href="@Url.Action("Index","Education")">Education</a></li>
										<li><a href="@Url.Action("Index","Experience")">Experience</a></li>
										<li><a href="@Url.Action("Index","Training")">Training</a></li>
										<li><a href="@Url.Action("Index","CertificationTest")">Certification Test</a></li>
										<li><a href="@Url.Action("Index","SportProgramming")">Sport Programming</a></li>
										<li><a href="@Url.Action("Index","Review")">Review/Comment</a></li>
									</ul>
								</li>
							</ul>
						</div>
					</div>
					<!-- /sidebar menu -->
				</div>
			</div>

			<!-- top navigation -->
			<div class="top_nav">
				<div class="nav_menu">
					<nav>
						<div class="nav toggle">
							<a id="menu_toggle"><i class="fa fa-bars"></i></a>
						</div>
						<ul class="nav navbar-nav navbar-right">
							<li class="">
								@if (User.Identity.IsAuthenticated)
								{
									<div class="col-sm-4" style="margin-top: 9px">
										<p>
											<a href="@Url.Action("SignOut", "Account",new { area = ""})" class="btn btn-default" style="float: right; color:black;">Sign out</a>
										</p>
									</div>
								}
							</li>
						</ul>
					</nav>
				</div>
			</div>
			<!-- /top navigation -->
			<!-- page content -->
			<div class="right_col" role="main">
				<div class="clearfix"></div>
				<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12">
						<div class="x_panel">
							<div class="x_title">
								<h2>Form <small>Experiences</small></h2>
								<ul class="nav navbar-right panel_toolbox">
									<li>
										<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
									</li>
								</ul>
								<div class="clearfix"></div>
							</div>

							@{ Html.RenderPartial("Create", new ExperienceViewModel() { CityViewModels = Model.ListOfViewModel2, UserViewModels= Model.ListOfViewModel3, KnowledgeViewModels = Model.ListOfViewModel4 }); }

							<div style="text-align:center; display: none" id="loader">
								<img src="~/Content/setting.gif" width="150" />
							</div>

							<div class="x_content">
								<table id="datatable-buttons" class="table table-striped table-bordered">
									<thead>
										<tr>
											<th>Id</th>
											<th>Company Name</th>
											<th>Count Experience</th>
											<th>City Id</th>
											<th>Name</th>
											<th>Country</th>
											<th>Knowledge id</th>
											<th>Knowledge Name</th>
											<th>Parent Name</th>
											<th>User Id</th>
											<th>Name</th>
											<th>Role</th>
											<th><i class="fa fa-edit"></i> | <i class="fa fa-trash"></i></th>
										</tr>
									</thead>

									<tbody>
										@foreach (var item in Model.ListOfViewModel)
										{
											<tr>
												<td>@Html.DisplayFor(model => item.Id)</td>
												<td>@Html.DisplayFor(model => item.CompanyName)</td>
												<td>@Html.DisplayFor(model => item.CountExperience)</td>
												<td>@Html.DisplayFor(model => item.CityId)</td>
												<td>@Html.DisplayFor(model => item.CityName)</td>
												<td>@Html.DisplayFor(model => item.City.Country.Name)</td>
												<td>@Html.DisplayFor(model => item.KnowledgeId)</td>
												<td>@Html.DisplayFor(model => item.KnowledgeName)</td>
												<td>@Html.DisplayFor(model => item.Knowledge.Knowledge2.Name)</td>
												<td>@Html.DisplayFor(model => item.UserId)</td>
												<td>@Html.DisplayFor(model => item.UserName)</td>
												<td>@Html.DisplayFor(model => item.User.Role.Name)</td>
												<td>
													<a class="btn btn-info" data-target="#myModal_@item.Id" data-toggle="modal"><i class="fa fa-pencil"></i></a>
													<a class="btn btn-danger" onclick="Delete('@Url.Action("Delete","Experience", new { id = item.Id})')"><i class="fa fa-trash"></i></a>

													<div class="modal active" id="myModal_@item.Id">
														<div class="modal-dialog">
															<div class="modal-content">
																@{ Html.RenderPartial("Edit", new ExperienceViewModel()
																	{
																		Id = item.Id,
																		CompanyName = item.CompanyName,
																		CountExperience = item.CountExperience,
																		CityViewModels = Model.ListOfViewModel2,
																		UserViewModels = Model.ListOfViewModel3,
																		KnowledgeViewModels = Model.ListOfViewModel4
																	}); }
															</div>
														</div>
													</div>
												</td>
											</tr>
										}
									</tbody>
								</table>

								<div class="btn-group">
									@Html.PageLinks(Model.PageInfo, x => Url.Action("Index", new { page = x }))
								</div>

							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- /page content -->

		</div>
	</div>

</body>

<script>

	function Delete(url, id) {
		if (confirm('Are you sure to delete this record ?')) {
			$.ajax({
				type: 'POST',
				url: url,
				success: function (data) {
					window.location.reload();
				}
			});
		}
	}

</script>